### ISSUE TITLE
Hardcoded JWT signing key

### ISSUE THREAD

**Issue by luco5826** [luco5826/group03-jwticket#2]
Keys should be kept secret and not be hardcoded in the software (nor versioned on GitHub).

We could set and environment variable to store the key and access it everytime it is needed. This should also make any key modification easier in the future

**Comment by fxbrit** [comment]
```kotlin
val keyString: String = System.getenv("jwt_testing_key") ?: "" 
```

could be done this way but empty string would throw exception because hmac requires 64-bit key. we would need to catch that.

**Comment by fxbrit** [comment]
in a separate branch I tried to solve this using the `@Value` annotation but it seems like I'm failing to read the properties file -> https://github.com/luco5826/group03-jwticket/commit/7dfebebc4ad3d8e86f49f7ce087635bad1829778

any idea?

**Comment by Ale142** [comment]
@fxbrit there was a dependency missing in the `TicketingService` class constructor: when spring tries to create the `TicketingController` and `TicketingService` which depends on, the key remains not initialized and an expectation is thrown and prevents the creation of the other two beans (service and controller). 

The fix for me was to remove the `lateinit var key` and add it in the primary constructor of the `Ticketing Service` class with the dependency.
```kotlin
class TicketingService(@Value("\${jwt.key}") private val key: String) {...}
```

I'll push the changes into your branch 55106c0

**Comment by fxbrit** [comment]
nice! I propagated the changes to unit and integration testing + opened a PR.

> (nor versioned on GitHub)

also, should we untrack the properties file?
